//! This file is autogenerated! Edit in meta/scripts/GenerateMetaData.ts

export const metadata = {
  commitHash: "7799ce5",
  fullCommitHash: "7799ce591a1e969096ba7092bc53c52b0207894d",
  commitDate: "2025-07-07T16:24:17+02:00",
  branch: "main",
  commitUrl: ""
};
